# SPDX-License-Identifier: GPL-2.0
# Taken from Linux
# That's our default target when none is given on the command line
PHONY := __all
__all:

this-makefile := $(lastword $(MAKEFILE_LIST))

# Do not use make's built-in rules and variables
# (this increases performance and avoids hard-to-debug behaviour)
MAKEFLAGS += -rR

export objtree := .
export srcroot := $(realpath $(dir $(this-makefile)))
export srctree := $(srcroot)

KCONFIG_CONFIG	?= .config
export KCONFIG_CONFIG

HOSTCC	= gcc
HOSTCXX	= g++
HOSTPKG_CONFIG	= pkg-config

#some stuff removed!
KBUILD_HOSTCFLAGS := -I $(srctree)/scripts/include
KBUILD_HOSTCXXFLAGS := -I $(srctree)/scripts/include

clean-targets := %clean mrproper
no-dot-config-targets := $(clean-targets)
single-targets := %.a %.i %.ko %.lds %.ll %.lst %.mod %.o %.rsi %.s %/

config-build	:=
mixed-build	:=
need-config	:= 1
ifneq ($(filter $(no-dot-config-targets), $(MAKECMDGOALS)),)
    ifeq ($(filter-out $(no-dot-config-targets), $(MAKECMDGOALS)),)
        need-config :=
    endif
endif

ifneq ($(filter %config,$(MAKECMDGOALS)),)
    config-build := 1
    ifneq ($(words $(MAKECMDGOALS)),1)
        mixed-build := 1
    endif
endif

# We cannot build single targets and the others at the same time
ifneq ($(filter $(single-targets), $(MAKECMDGOALS)),)
    single-build := 1
    ifneq ($(filter-out $(single-targets), $(MAKECMDGOALS)),)
        mixed-build := 1
    endif
endif

# For "make -j clean all", "make -j mrproper defconfig all", etc.
ifneq ($(filter $(clean-targets),$(MAKECMDGOALS)),)
    ifneq ($(filter-out $(clean-targets),$(MAKECMDGOALS)),)
        mixed-build := 1
    endif
endif

ifdef mixed-build
# ===========================================================================
# We're called with mixed targets (*config and build targets).
# Handle them one by one.

PHONY += $(MAKECMDGOALS) __build_one_by_one

$(MAKECMDGOALS): __build_one_by_one
	@:

__build_one_by_one:
	$(Q)set -e; \
	for i in $(MAKECMDGOALS); do \
		$(MAKE) -f $(srctree)/Makefile $$i; \
	done

else # !mixed-build

include $(srctree)/scripts/Kbuild.include

AR		= ar
LEX		= flex
YACC		= bison

# Use USERINCLUDE when you must reference the UAPI directories only.
USERINCLUDE    := \
                -include $(srctree)/include/linux/kconfig.h

# Use LINUXINCLUDE when you must reference the include/ directory.
LINUXINCLUDE    := \
		-I$(srctree)/include \
		-I$(objtree)/include \
		$(USERINCLUDE)

# Files to ignore in find ... statements

export HOSTCC KBUILD_HOSTCFLAGS HOSTPKG_CONFIG
export AR LEX YACC
export HOSTCXX
export KBUILD_HOSTCXXFLAGS

export LINUXINCLUDE

export RCS_FIND_IGNORE := \( -name .git \) -prune -o

PHONY += scripts_basic
scripts_basic:
	$(Q)$(MAKE) $(build)=scripts/basic

ifdef config-build
# ===========================================================================
# *config targets only - make sure prerequisites are updated, and descend
# in scripts/kconfig to make the *config target

#dependencies removed!!!!
config: scripts_basic FORCE
	$(Q)$(MAKE) $(build)=scripts/kconfig $@

%config: scripts_basic FORCE
	$(Q)$(MAKE) $(build)=scripts/kconfig $@
else # !config-build

PHONY += all
__all: all

KBUILD_BUILTIN := y

export KBUILD_BUILTIN

ifdef need-config
include $(objtree)/include/config/auto.conf
endif

ifdef need-config
# Read in dependencies to all Kconfig* files, make sure to run syncconfig if
# changes are detected. This should be included after arch/$(SRCARCH)/Makefile
# because some architectures define CROSS_COMPILE there.
include include/config/auto.conf.cmd

$(KCONFIG_CONFIG):
	@echo >&2 '***'
	@echo >&2 '*** Configuration file "$@" not found!'
	@echo >&2 '***'
	@echo >&2 '*** Please run some configurator (e.g. "make oldconfig" or'
	@echo >&2 '*** "make menuconfig" or "make xconfig").'
	@echo >&2 '***'
	@/bin/false

# The actual configuration files used during the build are stored in
# include/generated/ and include/config/. Update them if .config is newer than
# include/config/auto.conf (which mirrors .config).
#
# This exploits the 'multi-target pattern rule' trick.
# The syncconfig should be executed only once to make all the targets.
# (Note: use the grouped target '&:' when we bump to GNU Make 4.3)
#
# Do not use $(call cmd,...) here. That would suppress prompts from syncconfig,
# so you cannot notice that Kconfig is waiting for the user input.
%/config/auto.conf %/config/auto.conf.cmd %/generated/autoconf.h %/generated/rustc_cfg: $(KCONFIG_CONFIG)
	$(Q)$(kecho) "  SYNC    $@"
	$(Q)$(MAKE) -f $(srctree)/Makefile syncconfig
endif # need-config

build-dir	:= .
clean-dirs	:= .

endif # config-build
endif # mixed-build